# Generated by Django 2.2.13 on 2020-10-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='re_password',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(default=False),
        ),
    ]
