# Generated by Django 2.2.13 on 2020-10-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201023_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postDate',
            new_name='date',
        ),
    ]
