# Generated by Django 2.2.13 on 2020-10-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201023_2347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='RegistrationDetail',
        ),
    ]
