# Generated by Django 3.1.2 on 2020-10-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201028_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date', 'time']},
        ),
    ]
