# Generated by Django 3.1.2 on 2020-10-28 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201028_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
