# Generated by Django 3.1.2 on 2020-11-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201124_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['last_name', 'first_name', 'email']},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='first_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
