# Generated by Django 3.1.2 on 2020-11-24 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201124_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='picture',
        ),
    ]
