# Generated by Django 3.1.2 on 2020-10-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201027_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name', 'email']},
        ),
    ]
